[package]
name = "uuid-tld"
version = { workspace = true }
edition = { workspace = true }
# license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = "1.81"

[[bin]]
name = "uuid-tld"
path = "src/bin/guest.rs"
required-features = ["risc0"]
test = false

[dependencies]
sdk = { path = "../../contract-sdk", package = "hyle-contract-sdk" }
borsh = "1.5.5"

anyhow = { version = "1.0.95", optional = true }
risc0-zkvm = { version = "1.2.3", default-features = false, optional = true, features = [
    'std',
] }
client_sdk = { path = "../../client-sdk", package = "client-sdk", default-features = false, features = [
    "risc0",
], optional = true }
uuid = { version = "1.12.1", default-features = false, features = [
    "std",
    "v4",
    "fast-rng",
] }
rand = { version = "0.9", default-features = false }
rand_seeder = { version = "0.4.0", default-features = false }

[features]
default = []
client = ["dep:client_sdk", "dep:anyhow"]
risc0 = ["dep:risc0-zkvm", "sdk/risc0"]
