[package]
name = "hyle-uuid-tld"
description = "Hyli Smart Contract"
license-file = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = "1.81"

[[bin]]
name = "uuid-tld"
path = "src/main.rs"
required-features = ["risc0"]
test = false

[dependencies]
sdk = { workspace = true }
borsh = "1.5.6"

risc0-zkvm = { version = "2.0.2", default-features = false, optional = true, features = [
  'std',
] }
client-sdk = { workspace = true, default-features = false, features = [
  "risc0",
], optional = true }
uuid = { version = "1.16.0", default-features = false }
rand = { version = "0.9", default-features = false }
rand_seeder = { version = "0.4.0", default-features = false }

[dev-dependencies]
risc0-zkvm = { version = "2.0.2", default-features = false, features = [
  'std',
  'prove',
] }

[features]
default = []
client = ["dep:client-sdk"]
risc0 = ["dep:risc0-zkvm", "sdk/risc0"]
