[package]
name = "hyle-smt-token"
description = "Hyli Smart Contract"
license = "MIT"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = "1.81"

[[bin]]
name = "smt-token"
path = "src/main.rs"
required-features = ["risc0"]
test = false

[[example]]
name = "smt-token-runner"
path = "examples/host.rs"

[dependencies]
anyhow = "1.0.98"
sdk = { workspace = true, features = ["smt"] }
sha2 = "=0.10.8" # precompile patched at workspace root
borsh = { version = "1.5.5", features = ["derive"] }
sparse-merkle-tree = "0.6.1"
serde = { version = "1.0", default-features = false, features = [
  "derive",
  "alloc",
] }

risc0-zkvm = { version = "2.0.2", default-features = false, optional = true, features = [
  'std',
] }
client-sdk = { workspace = true, features = [
  "risc0",
  "rest",
  "indexer",
], optional = true }

[dev-dependencies]
# Active client feature for tests
hyle-smt-token = { path = ".", features = ["client"] }
tokio = { version = "1.44.2", features = ["full", "tracing"] }

risc0-zkvm = { version = "2.0.2", default-features = false, features = [
  'std',
  'prove',
] }
mockall = "0.13.0"
test-log = { version = "0.2.17", features = [
  "color",
  "trace",
], default-features = false }

[features]
default = []
client = ["dep:client-sdk", "sdk/tracing"]
risc0 = ["dep:risc0-zkvm", "sdk/risc0"]
