[package]
name = "risc0-recursion"
version = { workspace = true }
edition = { workspace = true }
# license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = "1.81"

[[bin]]
name = "risc0-recursion"
required-features = ["risc0"]
path = "src/bin/guest.rs"
test = false

[[example]]
name = "risc0-recursion-runner"
path = "examples/host.rs"

[dependencies]
sdk = { path = "../../contract-sdk", package = "hyle-contract-sdk" }
serde = { version = "1.0.217", features = ["derive"] }

risc0-zkvm = { version = "1.2.1", default-features = false, optional = true, features = [
    'std',
] }

[dev-dependencies]
# Activate client in examples.
risc0-recursion = { path = ".", features = ["client"] }

anyhow = "1.0.95"
bincode = "2.0.0-rc.3"
borsh = "1.5.5"
hex = "0.4.3"
hydentity = { path = "../hydentity", features = ["client"] }
hyle-contracts = { path = ".." }
client-sdk = { path = "../../client-sdk" }
sdk = { path = "../../contract-sdk", package = "hyle-contract-sdk", features = [
    "full-model",
] }
tokio = { version = "1.42.0" }
risc0-zkvm = { version = "1.2.1", default-features = false, features = [
    'std',
    'prove',
] }
tempfile = "3.15.0"
test-log = { version = "0.2.17", features = [
    "color",
    "trace",
], default-features = false }

[features]
default = []
client = []
risc0 = ["dep:risc0-zkvm", "sdk/risc0"]
