[package]
name = "hyle-risc0-recursion"
description = "Hyli Smart Contract"
license-file = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = "1.81"

[[bin]]
name = "risc0-recursion"
required-features = ["risc0"]
path = "src/bin/guest.rs"
test = false

[[example]]
name = "risc0-recursion-runner"
path = "examples/host.rs"

[dependencies]
sdk = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }

risc0-zkvm = { version = "2.0.2", default-features = false, optional = true, features = [
  'std',
] }

[dev-dependencies]
# Activate client in examples.
hyle-risc0-recursion = { path = ".", features = ["client"] }

client-sdk = { workspace = true }
sdk = { workspace = true, features = ["full-model"] }

anyhow = "1.0.98"
borsh = "1.5.6"
hex = "0.4.3"
hydentity = { workspace = true, features = ["client"] }
hyle-contracts = { path = ".." }
tokio = { version = "1.44.2" }
risc0-zkvm = { version = "2.0.2", default-features = false, features = [
  'std',
  'prove',
] }
tempfile = "3.20.0"
test-log = { version = "0.2.17", features = [
  "color",
  "trace",
], default-features = false }

[features]
default = []
client = []
risc0 = ["dep:risc0-zkvm", "sdk/risc0"]
