name: Create a PR to update contracts

on:
  push:
    branches:
      - feat/add_ci_workflow_to_update_contracts
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Récupère tout l'historique pour éviter les problèmes
      - name: Install rzup
        run: |
          curl -L https://risczero.com/install | bash
          /home/runner/.risc0/bin/rzup install

      - name: Run contract update command
        run: |
          cargo build -p hyle-contracts --features build -vv

      - name: Check for changes
        run: |
          git diff --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

      - name: Configure Git
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch
        if: env.CHANGES_DETECTED == 'true'
        run: |
          BRANCH_NAME="contracts-update/$(date +%s)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Commit and push changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git add -A
          git commit -m "Automated contracts update: changes from command execution"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        if: env.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Automated Update"
          body: "This is an automated PR generated by GitHub Actions."
          labels: "automation, bot"
          reviewers: "your-github-username"
